### ISSUE TITLE
Infografía Desarrollo de software 

### ISSUE THREAD

**Issue by edgarmauricio123** [SistemasTecTlaxiaco/actividad-1-infografia-edgarmauricio123#1]
[Infografía Desarrollo de Software.pdf](https://github.com/user-attachments/files/16821421/Infografia.Desarrollo.de.Software.pdf)

**Comment by Jaczibeth** [comment]
De acuerdo a la rubrica tienes un 18 %  
presenta falta de link , conceptos.....

**Comment by josealfredo79** [comment]
bien hecho y revisado..
